version: '3'

services:
  proxy:
    image: staticfloat/nginx-certbot
    restart: always
    environment:
      CERTBOT_EMAIL: "lancemenz0099@gmail.com"
    ports:
      - 80:80
      - 443:443
      volumes:
        - ./conf.d:/etc/nginx/user.conf.d:ro
        - letsencrypt:/etc/letsencrypt
volumes:
  letsencrypt:
